### ISSUE TITLE
Blindness rework isn't fully complete

### ISSUE THREAD

**Issue by DoctoreMad** [RoleplayRascal/-8ch-station#107]
Amognst other things...

You no longer get darkness overlay while sleeping
You no longer get darkness overlay while in crit, though it will show the white light coming closer and closer

**Comment by KyleBaran** [comment]
Known issue. Missed a few things here and there. Specifically, it was split into having a "blindness" and "blindness intensity", instead of the just the former. I have updated it and pushed a fix into the next compile; HOPEFULLY it should be fixed, but keep an eye out for any other weirdness (eg permanent or too-short blindness, etc)

**Comment by KyleBaran** [comment]
Code is apparently re-compiled and good to go. Again, look out for any shortfalls
