### ISSUE TITLE
pest spray doesnt actually do anything

### ISSUE THREAD

**Issue by GeneralGoose** [RoleplayRascal/-8ch-station#88]
5/10 pests in a tray, poured a whole can in, still 5/10 
so pests are pretty much unkillable i guess

**Comment by chaosyourgod** [comment]
we know about it

**Comment by GeneralGoose** [comment]
should note that pests seem to disappear if the tray gets emptied in any way

**Comment by KyleBaran** [comment]
Should be fixed next compile - sort of.

You need to use a "pest spray" bottle on the tray. Doing so will remove 3 levels of pests. This is coded as an object interaction, rather than a reagent/reaction. So basically the chems in the bottle shouldn't matter as long as it has _something_ to spray. I'll fix it fully later, but this will at least let you muck around with it in the meantime.

**Comment by KyleBaran** [comment]
Closing issue, but please re-make it if there are more bugs.
